-- Script de reprodução preparado para o portfólio. Não sobrescreve tabela existente.
CREATE TABLE public.rh_funcionarios (
    ID_Funcionario INTEGER PRIMARY KEY,
    Nome TEXT,
    Genero TEXT,
    Data_Nascimento TIMESTAMP,
    Idade INTEGER,
    Estado TEXT,
    Cidade TEXT,
    Departamento TEXT,
    Cargo TEXT,
    Nivel TEXT,
    Data_Admissao TIMESTAMP,
    Data_Desligamento TIMESTAMP,
    Status TEXT,
    Salario NUMERIC,
    Tipo_Contrato TEXT,
    Modalidade TEXT,
    Avaliacao_Desempenho NUMERIC,
    Satisfacao NUMERIC,
    Horas_Treinamento INTEGER,
    Promovido TEXT,
    Ultima_Promocao TIMESTAMP,
    Ferias_Dias INTEGER,
    Faltas INTEGER,
    Horas_Extras NUMERIC,
    Salario_Anterior NUMERIC,
    Motivo_Desligamento TEXT,
    Ano_Admissao INTEGER,
    Ano_Desligamento NUMERIC,
    Tempo_Empresa_Anos NUMERIC
);
